### PR TITLE
Use json to convert parameters to string

### PR DESCRIPTION
**Pull request by kayibal**
Tested this with luigi==2.1.1 and it works better as it serializes objects as luigi expects it. In the corresponding instantiation method.

### CODE REVIEW

**Comment by samuell** [comment]
Many thanks @kayibal ! Will have a look at this shortly.

**Comment by samuell** [comment]
Sorry for the delay ... is hoping to perform some testing of this before merging, just for making sure nothing breaks. Will get back shortly.

**Comment by kayibal** [comment]
No problems :) I have been using it for a few month's so far seems to be working fine ;)

**Comment by samuell** [comment]
Getting at this tonight ... having hope it might solve some annoying warning messages I've seen with the latest Luigi ...right? :)

**Comment by samuell** [comment]
Merged now. Many thanks, @kayibal !

**Pull request merged**
