### PR TITLE
Custom aws batch job name

### PR DESCRIPTION
**Pull request by sminot**
I tested this out on my workflows and it appears to work.

### CODE REVIEW

**Comment by samuell** [comment]
Hi guys, @sminot @jgolob, 

You seem to have been doing a lot of work on this. Are you interested in taking over maintenance of sciluigi?

**Comment by sminot** [comment]
Sorry, I didn't mean to open a PR against pharmbio/sciluigi, my mistake

**Comment by samuell** [comment]
@sminot Okay, no worries! :) Still, the question about maintainership remains open, just so you know :)

**Comment by sminot** [comment]
Good to know, I'll defer to @jgolob on that one – I certainly am not qualified

**Pull request closed without merging**
